;; -*- mode: eask; lexical-binding: t -*-

(package "lgtm"
         "1.0.0"
         "Code review UI for Emacs")

(website-url "ravit.ch")
(keywords "git" "code-review")

(files "lgtm.el"
       "lgtm-core.el"
       "lgtm-github.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "29.1")
(depends-on "ghub")
(depends-on "magit-section")
(depends-on "posframe")

