name = "LgtmLean"
version = "0.1.0"
defaultTargets = ["lgtmlean", "extractor"]

[[lean_lib]]
name = "LgtmLean"

[[lean_lib]]
name = "Extractor"

[[lean_exe]]
name = "lgtmlean"
root = "Main"

[[lean_exe]]
name = "extractor"
root = "Extractor"
supportInterpreter = true
